---
repos:
  # Backend
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^((custom_components/knx_panel)/.+)?[^/]+\.py$
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.6.0
          - pydocstyle==6.0.0
        files: ^(custom_components/knx_panel)/.+\.py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --resolve-all-configs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
      - id: trailing-whitespace
        files: ^((custom_components/knx_panel)/.+)?[^/]+\.py$
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.3.5
    hooks:
      # Run `pre-commit run --hook-stage manual python-typing-update --all-files` manually
      # from time to time to update python typing syntax.
      # Will require manual work, before submitting changes!
      - id: python-typing-update
        stages: [manual]
        args:
          - --py39-plus
          - --force
          - --keep-updates
        files: ^(custom_components/knx_panel)/.+\.py$
  # Frontend
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        files: frontend/src/.
  - repo: https://github.com/awebdeveloper/pre-commit-tslint
    rev: v0.0.2
    hooks:
      - id: tslint
        args:
          - --fix
        additional_dependencies: [ 'tslint@5.0.0' ]