name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
          cache-dependency-path: frontend/package-lock.json
      - run: cd frontend && npm ci
      - run: |
          mkdir -p dist/
          cd custom_components/knx_panel
          zip ../../dist/knx_panel.zip ./*
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
